apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: component-example
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: sample-component-name
    app.kubernetes.io/part-of: my-application
  name: component-example
  namespace: default
spec:
  port:
    targetPort: 8080
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: component-example
    weight: 100
status: {}
